export const green = '#12B575'
export const green_gradient = ''
export const red = '#F52658'
export const dark_blue = '#222C54'
export const light_grey = '#989CAD'
export const grey = '#696683'
export const extra_light_grey = '#EFEFEF'
export const white = '#fff'
